spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/location?registerGdal=true
    username: postgres
    password: 123456789
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect